#2016.6.23
###Exceptions:
C++: on errors, a function *raises an exception* </br>
What happens? </br>
By default, execution stops </br>
But we can write handler to catch exceptions to deal with them. </br>
vector<T>.at throws exception std::out_of_range when it fails
<pre><code>
#include < stdexpect >
...
try {
 cout << v.at(1000) << endl;  
}
 catch {out_of_range) {
  cerr << ""range arror\n";
}
</code></pre>

Now consider:
<pre><code>
void f() {
 throw out.of.range {"f"}; //raise an exception
}
void g() { f();}
void h() { g();}

int main() {
 try {h();}
 catch (out_of_range) {...
 }
</code></pre>
What happens: </br>
main calls h </br>
h calls g </br>
g calls f </br>
f throws out of rangec </br>
g has no handler for out.of.range </br>
control goes back through the call chain (unwinds the stack) </br>
until a handler is found

Control goes all the way back to main </br>
main handles the exception </br>
If no handler in the entire call chain, program terminates

What is out_of_range?  </br>
A class. </br>
throw out-of-range {"f"}; //invokes ctor with argument"f" (auxiliary info) and throws it </br>
to example that info:
<pre><code>
try {...}
catch (out_of_range ex) {
 cout << ex.what() << endl;
}
</code></pre>

A handler might do part of the recovery job: </br>
execute some corrective code and throw another exception
<pre><code>
try {...}
catch (SomeErrorType s) {
 ...
 throw SomeOtherError(...);
}
// or rethrow the same exception
try {...}
catch (SomeErrorType s) {
 ...
 throw;
}
</code></pre>
throw s; : </br>
s may be a subtype of SomeErrorType </br>
rethrows a new exception of type SomeErrorType </br>
throw; : </br>
actual type of s is retained

A handler can act as a catch-all:
<pre><code>
try {...}
catch(...) { // catches all exceptions
...
}
</code></pre>
You can throw anything you want, do not have to be objects

Define your own classes for use appropriate existing ones </br>
for errors:
<pre><code>
class badInput{};
try {
 int n;
 if(!(cin >> n))throw badInput();
}

catch (badInput &) { //catches by reference, presents slicing
 cerr << ...;
}
</code></pre>

Note:
<pre><code>
class BaseEx{};
class DerivedEx: public BaseEx{};
void f() {
 DerivedEx d;
 BaseEx &b = d;
 throw b;
} 
...
try {...}
catch (DerivedEx &d) {...}
catch (BaseEx &b) {...}
</code></pre>
Which handler runs? </br>
BaseEx handler runs. </br>
the type pf the *reference* (ie. the static type of the object) determines the handler

**Some standard exceptions**: </br>
- length_error: attempt to resize strings/vectors that are too long </br>
- bad_alloc: *new* fails
- ios::failure: i/o stream failure


######WARNING:
######NEVER EVER let a dtor throw an exception!!!
if the dtor is executed during stack unwinding while dealing with another exception </br>
you now have two active unhandled exceptions </br>
the program will terminate immidiately(no recovery)

###Design pattern continue:
Guiding Principle: program to interfaces, not implementations </br>
- abstract base classes define the interface </br>
 - work with pointers to acbstract base classes and call their methods
 - concrete subclasses can be swapped in to specialize behaviour
 - abstraction over a variety of behaviors
 
<pre><code>
 class List {
  ...
  public:
   class Iterator { 
   ...
  }
};

class AbstractIterator {
 public:
  virtual int&operator*()=0;
  virtual AbstractIterator &operator++()=0;
  virtual bool opereator != (...)=0;
  virtual ~AbstractIterator();
};

class Set {
 public:
  class Iterator: Public AbstractIterator { 
  ...
  };
</code></pre>

<pre><code>
template <typrname T>
void foreach(AbstractIterator start, AbstractIterator end, T (*f)(int)) {
 while (start != end) {
  f(*start); //f must be callable entity
  ++start;;
 }
} //works either lists or sets
</code></pre>

###Observer Pattern:
publish: 
one class </br>
publisher/subject </br>
source of date
...
